/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import { Contract as MulticallContract } from "@hovoh/ethers-multicall";
import type {
  PayableFactory,
  PayableFactoryInterface,
  PayableFactoryMulticall,
} from "../../../v0.6.4/Payable/PayableFactory";

const _abi = [
  {
    inputs: [],
    name: "newPayable",
    outputs: [
      {
        internalType: "contract Payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class PayableFactory__factory {
  static readonly abi = _abi;
  static createInterface(): PayableFactoryInterface {
    return new utils.Interface(_abi) as PayableFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PayableFactory {
    return new Contract(address, _abi, signerOrProvider) as PayableFactory;
  }

  static multicall(address: string): PayableFactoryMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as PayableFactoryMulticall;
  }
}
