/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import { Contract as MulticallContract } from "@hovoh/ethers-multicall";
import type {
  ISimpleToken,
  ISimpleTokenInterface,
  ISimpleTokenMulticall,
} from "../../v0.8.9/ISimpleToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISimpleToken__factory {
  static readonly abi = _abi;
  static createInterface(): ISimpleTokenInterface {
    return new utils.Interface(_abi) as ISimpleTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISimpleToken {
    return new Contract(address, _abi, signerOrProvider) as ISimpleToken;
  }

  static multicall(address: string): ISimpleTokenMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as ISimpleTokenMulticall;
  }
}
