/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import { Contract as MulticallContract } from "@hovoh/ethers-multicall";
import type {
  NestedLibrary,
  NestedLibraryInterface,
  NestedLibraryMulticall,
} from "../../../../v0.8.9/nested/b/NestedLibrary";

const _abi = [
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class NestedLibrary__factory {
  static readonly abi = _abi;
  static createInterface(): NestedLibraryInterface {
    return new utils.Interface(_abi) as NestedLibraryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NestedLibrary {
    return new Contract(address, _abi, signerOrProvider) as NestedLibrary;
  }

  static multicall(address: string): NestedLibraryMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as NestedLibraryMulticall;
  }
}
